Repository oracle/create-database-app, pull requests merged in 2025-01, with the labels that each got.

#197 Vite migration and dependency updates
  templates/ords-remix-jwt-sample/README.md
  templates/ords-remix-jwt-sample/app/components/concerts/ConcertCard.tsx
  templates/ords-remix-jwt-sample/app/components/homepage/ArtistCard.tsx
  templates/ords-remix-jwt-sample/app/components/homepage/ConcertCard.tsx
  templates/ords-remix-jwt-sample/app/components/search/DatePicker.tsx
  templates/ords-remix-jwt-sample/app/root.tsx
  templates/ords-remix-jwt-sample/app/routes/private.tsx
  templates/ords-remix-jwt-sample/package.json
  templates/ords-remix-jwt-sample/postcss.config.mjs
  templates/ords-remix-jwt-sample/tsconfig.json
  templates/ords-remix-jwt-sample/vite.config.ts
Labels: OCA Verified, templates-ords-remix

#198 fix(deps): dependencies upgrade and removal to bump cross-spawn to v7.0.6 CVE GHSA-3xgq-45jj-v275
  package-lock.json
  package.json
Labels: OCA Verified

#200 fix(deps): bump node-react template to react v19.0 and eslint v9
  templates/app/index.cjs
  templates/app/utils/rest-services/connection.cjs
  templates/node-react/.eslintrc.cjs
  templates/node-react/eslint.config.mjs
  templates/node-react/package.json
  templates/node-react/src/App.jsx
Labels: OCA Verified, dependencies, templates-react

#199 fix(deps): bump node-jet template to JET v17.1
  templates/node-jet/oraclejetconfig.json
  templates/node-jet/package.json
  templates/node-jet/path_mapping.json
  templates/node-jet/src/index.html
  templates/node-jet/src/main.js
Labels: OCA Verified, dependencies, templates-jet

#201 bump node-react-todo template to react v19.0 and eslint v9
  templates/node-react-todo/.eslintrc.cjs
  templates/node-react-todo/eslint.config.mjs
  templates/node-react-todo/eslintrc.cjs
  templates/node-react-todo/package.json
  templates/node-react-todo/src/components/ToDoListFilter.jsx
  templates/node-react-todo/src/components/ToDoListInput.jsx
  templates/node-react-todo/src/components/TodoList.jsx
  templates/node-react-todo/src/components/TodoListFooter.jsx
  templates/node-react-todo/src/components/TodoListItems.jsx
  templates/node-react-todo/src/utils/utils.js
Labels: OCA Verified

#203 Bump node-angular template to angular 19.1
  templates/node-angular/.editorconfig
  templates/node-angular/.gitignore.template
  templates/node-angular/.vscode/extensions.json
  templates/node-angular/.vscode/launch.json
  templates/node-angular/.vscode/tasks.json
  templates/node-angular/README.md
  templates/node-angular/angular.json
  templates/node-angular/eslint.config.mjs
  templates/node-angular/package.json
  templates/node-angular/public/assets/.gitkeep
  templates/node-angular/public/assets/angular.svg
  templates/node-angular/public/assets/oracle.svg
  templates/node-angular/public/favicon.ico
  templates/node-angular/src/app/app.component.css
  templates/node-angular/src/app/app.component.html
  templates/node-angular/src/app/app.config.ts
  templates/node-angular/src/styles.css
  templates/node-angular/tsconfig.app.json
  templates/node-angular/tsconfig.json
  templates/node-angular/tsconfig.spec.json
Labels: OCA Verified

#204 Bump node-vue dependencies and migrated to ESLint flat config
  templates/node-vue/.eslintrc.cjs
  templates/node-vue/eslint.config.mjs
  templates/node-vue/package.json
  templates/node-vue/src/App.vue
  templates/node-vue/src/components/HelloWorld.vue
Labels: OCA Verified

#205 Updating ESLint config for node-jet template
  templates/node-jet/eslint.config.mjs
  templates/node-jet/package.json
  templates/node-jet/src/components/content/index.tsx
Labels: OCA Verified
